twig:
    file_name_pattern: '*.twig'
    paths:
        'vendor/sirvoy/twig-bulma-form-theme-bundle/views/Form': ~
    form_themes: ['bulma_layout.html.twig']
when@test:
    twig:
        strict_variables: true
